version: 0.2

phases:
  pre_build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.pytest.org/en/latest/goodpractices.html>
      - python setup.py pytest

      - aws cloudformation package --template template.yml --s3-bucket sitting-ducks --output-template-file template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
