AWSTemplateFormatVersion: 2010-09-09
Outputs:
  EBApplicationName:
    Description: EBApplicationName
    Export:
      Name:
        Fn::Sub: ${GalleryId}:EB:ApplicationName
    Value:
      Ref: EBApplication
  EBTemplateName:
    Description: EBConfigurationTemplate
    Export:
      Name:
        Fn::Sub: ${GalleryId}:EB:ConfigurationTemplate
    Value:
      Ref: EBConfigurationTemplate
Parameters:
  AppName:
    Default: SittingDucks
    Type: String
  GalleryId:
    Default: devtest
    Type: String
Resources:
  EBApplication:
    Properties:
      ApplicationName:
        Fn::Sub: ${GalleryId}_${AppName}
    Type: AWS::ElasticBeanstalk::Application
  EBConfigurationTemplate:
    Properties:
      ApplicationName:
        Ref: EBApplication
      OptionSettings:
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:elasticbeanstalk:healthreporting:system
        OptionName: SystemType
        Value: enhanced
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value:
          Ref: EBInstanceProfile
      SolutionStackName: 64bit Amazon Linux 2018.03 v2.7.3 running Python 3.6
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
  EBInstanceProfile:
    Properties:
      Path: /
      Roles:
      - Ref: EBInstanceProfileRole
    Type: AWS::IAM::InstanceProfile
  EBInstanceProfileRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
      - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
      - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth
      Path: /
    Type: AWS::IAM::Role
