AWSTemplateFormatVersion: 2010-09-09
Parameters:
  GalleryId:
    Type: String
  InstanceType:
    Default: t2.small
    Type: String
Resources:
  EBApplication:
    Description: The AWS Elastic Beanstalk application, which is a container used
      to deploy the correct application configuration.
    Properties:
      ApplicationName:
        Fn::Sub: ${GalleryId}app2
    Type: AWS::ElasticBeanstalk::Application
  EBApplicationVersion:
    Properties:
      ApplicationName:
        Ref: EBApplication
      Description: The application version number.
      SourceBundle:
        S3Bucket: sitting-ducks-codebuild
        S3Key: 936d7e2563b7d4c838cd956973dca00c
    Type: AWS::ElasticBeanstalk::ApplicationVersion
  EBConfigurationTemplate:
    Description: The AWS Elastic Beanstalk configuration template to be created for
      this project, which defines configuration settings used to deploy different
      versions of an application.
    Properties:
      ApplicationName:
        Ref: EBApplication
      Description: The name of the sample configuration template.
      OptionSettings:
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:elasticbeanstalk:healthreporting:system
        OptionName: SystemType
        Value: enhanced
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value:
          Ref: EBInstanceProfile
      SolutionStackName: 64bit Amazon Linux 2018.03 v2.7.3 running Python 3.6
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
  EBEnvironment:
    Description: The AWS Elastic Beanstalk deployment group where the application
      is deployed, which is made up of the Amazon EC2 Linux instances launched for
      this project.
    Properties:
      ApplicationName:
        Ref: EBApplication
      Description: The application to be deployed to the environment.
      EnvironmentName:
        Ref: EBApplication
      OptionSettings:
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value:
          Ref: InstanceType
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: EC2KeyName
        Value: debugkp
      - Namespace: aws:ec2:vpc
        OptionName: VPCId
        Value:
          Fn::ImportValue:
            Fn::Sub: ${GalleryId}:VPC:Id
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value:
          Fn::ImportValue:
            Fn::Sub: ${GalleryId}:SubnetPubA:Id
      TemplateName:
        Ref: EBConfigurationTemplate
      VersionLabel:
        Ref: EBApplicationVersion
    Type: AWS::ElasticBeanstalk::Environment
  EBInstanceProfile:
    Properties:
      Path: /
      Roles:
      - Ref: EBInstanceProfileRole
    Type: AWS::IAM::InstanceProfile
  EBInstanceProfileRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action: '*'
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: donotdothisathome
    Type: AWS::IAM::Role
