AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sitting-ducks

    Sample SAM Template for sitting-ducks

Parameters:
    MemSize:
        Type: Number
        Default: 128
        AllowedValues: [128, 512, 1024, 2048]
    TimeLimit:
        Type: Number
        Default: 10
Globals:
    Function:
        Timeout: !Ref TimeLimit
        MemorySize: !Ref MemSize

Resources:
    FiboIterFn:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./src/main/python/
            Handler: sducks.lambdas.fibo_iter
            Runtime: python3.6
            Events:
                FiboIterApi:
                    Type: Api
                    Properties:
                        Path: /fib_iter
                        Method: get
    FiboRecFn:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./src/main/python/
            Handler: sducks.lambdas.fibo_rec
            Runtime: python3.6
            Events:
                FiboRecApi:
                    Type: Api
                    Properties:
                        Path: /fib_rec
                        Method: get
    FiboMemoFn:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./src/main/python/
            Handler: sducks.lambdas.fibo_memo
            Runtime: python3.6
            Events:
                FiboMemoApi:
                    Type: Api
                    Properties:
                        Path: /fib_memo
                        Method: get
    FiboGenFn:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./src/main/python/
            Handler: sducks.lambdas.fibo_gen
            Runtime: python3.6
            Events:
                FiboGenFnApi:
                    Type: Api
                    Properties:
                        Path: /fib_gen
                        Method: get
Outputs:
    APIEndpoint:
      Description: "API endpoint"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
