AWSTemplateFormatVersion: 2010-09-09

Parameters:
  GalleryId:
    Type: String
    Default: devtest
  AppName:
    Type: String
    Default: SittingDucks

Resources:
  EBInstanceProfileRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth


  EBInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: /
      Roles:
        - !Ref EBInstanceProfileRole

  EBApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Sub '${GalleryId}_${AppName}'

  EBConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref 'EBApplication'
      SolutionStackName: "64bit Amazon Linux 2018.03 v2.7.3 running Python 3.6"
      OptionSettings:
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:elasticbeanstalk:healthreporting:system
        OptionName: SystemType
        Value: enhanced
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: MonitoringInterval
        Value: "1 minute"
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: !Ref EBInstanceProfile       

Outputs:
  EBApplicationName:
    Description: EBApplicationName
    Value: !Ref EBApplication
    Export:
      Name: !Sub ${GalleryId}:EB:ApplicationName
  EBTemplateName:
    Description: EBConfigurationTemplate
    Value: !Ref EBConfigurationTemplate
    Export:
      Name: !Sub ${GalleryId}:EB:ConfigurationTemplate
