Parameters:
  GalleryId:
    Default: devnest
    Type: String
Resources:
  BaseHAVPC:
    Properties:
      Parameters:
        GalleryId:
          Ref: GalleryId
      TemplateURL: https://s3.amazonaws.com/sitting-ducks-codebuild/4650bc7fa1d8185a1715dad9177002e7.template
    Type: AWS::CloudFormation::Stack
  BeanstalkApp:
    DependsOn: BaseHAVPC
    Properties:
      Parameters:
        GalleryId:
          Ref: GalleryId
      TemplateURL: https://s3.amazonaws.com/sitting-ducks-codebuild/9eb228ca5b3a032b373871072f767ac6.template
    Type: AWS::CloudFormation::Stack
  SmallDucks:
    DependsOn: BeanstalkApp
    Properties:
      Parameters:
        GalleryId:
          Ref: GalleryId
      TemplateURL: https://s3.amazonaws.com/sitting-ducks-codebuild/f3c5f8dc305f83f0d8a093441f46fcbe.template
    Type: AWS::CloudFormation::Stack
