Parameters:
  GalleryId:
    Default: devnest
    Type: String
Resources:
  BaseHAVPC:
    Properties:
      Parameters:
        GalleryId:
          Ref: GalleryId
      TemplateURL: https://s3.amazonaws.com/sitting-ducks-codebuild/4650bc7fa1d8185a1715dad9177002e7.template
    Type: AWS::CloudFormation::Stack
  BeanstalkApp:
    DependsOn: BaseHAVPC
    Properties:
      Parameters:
        GalleryId:
          Ref: GalleryId
      TemplateURL: https://s3.amazonaws.com/sitting-ducks-codebuild/a1109d4377e9b76d42c3ffd432b52384.template
    Type: AWS::CloudFormation::Stack
  SmallDucks:
    DependsOn: BeanstalkApp
    Properties:
      Parameters:
        GalleryId:
          Ref: GalleryId
      TemplateURL: https://s3.amazonaws.com/sitting-ducks-codebuild/05ab179bfada91626e434a6686db76e6.template
    Type: AWS::CloudFormation::Stack
