Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar project ID used to name project resources and create roles.
  InstanceType:
    Type: String
    Description: The type of Amazon EC2 Linux instances that will be launched for this project.
  KeyPairName:
    Type: String
    Description: The name of an existing Amazon EC2 key pair in the region where the project is created, which you can use to SSH into the new Amazon EC2 Linux instances.
  VpcId:
    Type: String
    Description: The ID of the Amazon Virtual Private Cloud (VPC) used for the new Amazon EC2 Linux instances.
  SubnetId:
    Type: String
    Description: The name of the VPC subnet used for the new Amazon EC2 Linux instances launched for this project.
  SolutionStackName:
    Type: String
    Description: The software stack used to launch environments and configure instances in AWS Elastic Beanstalk.
  EBTrustRole:
    Type: String
    Description: The service role in IAM for AWS Elastic Beanstalk to be created for this project.
  EBInstanceProfile:
    Type: String
    Description: The IAM role that will be created for the Amazon EC2 Linux instances.
Resources:
  BeanstalkFlask:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectId: !Ref ProjectId
        InstanceType: !Ref InstanceType
        KeyPairName: !Ref KeyPairName
        VpcId: !Ref VpcId
        SubnetId: !Ref SubnetId
        SolutionStackName: !Ref SolutionStackName
        EBTrustRole: !Ref EBTrustRole
        EBInstanceProfile: !Ref EBInstanceProfile
      TemplateURL: cfn-beanstalk-flask.yml