AWSTemplateFormatVersion: 2010-09-09
Conditions:
  UseSubnet:
    Fn::Not:
    - Fn::Equals:
      - Ref: SubnetId
      - subnet-none
Parameters:
  EBInstanceProfile:
    Description: The IAM role that will be created for the Amazon EC2 Linux instances.
    Type: String
  EBTrustRole:
    Description: The service role in IAM for AWS Elastic Beanstalk to be created for
      this project.
    Type: String
  InstanceType:
    Description: The type of Amazon EC2 Linux instances that will be launched for
      this project.
    Type: String
  KeyPairName:
    Description: The name of an existing Amazon EC2 key pair in the region where the
      project is created, which you can use to SSH into the new Amazon EC2 Linux instances.
    Type: String
  ProjectId:
    Description: AWS CodeStar project ID used to name project resources and create
      roles.
    Type: String
  SolutionStackName:
    Description: The software stack used to launch environments and configure instances
      in AWS Elastic Beanstalk.
    Type: String
  SubnetId:
    Default:
      Fn::ImportValue: ${AWS::StackName}:SubnetPubA:Id
    Type: String
  VpcId:
    Default:
      Fn::ImportValue: ${AWS::StackName}:VPC:Id
    Description: The ID of the Amazon Virtual Private Cloud (VPC) used for the new
      Amazon EC2 Linux instances.
    Type: String
Resources:
  EBApplication:
    Properties:
      ApplicationName:
        Fn::Sub: ${ProjectId}app
    Type: AWS::ElasticBeanstalk::Application
  EBApplicationVersion:
    Properties:
      ApplicationName:
        Ref: EBApplication
      SourceBundle:
        S3Bucket: sitting-ducks-codebuild
        S3Key: e1fe66a22d6f6ed2eef61bca9b67fa2e
    Type: AWS::ElasticBeanstalk::ApplicationVersion
  EBConfigurationTemplate:
    Properties:
      ApplicationName:
        Ref: EBApplication
      OptionSettings:
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: SingleInstance
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: ServiceRole
        Value:
          Ref: EBTrustRole
      - Namespace: aws:elasticbeanstalk:healthreporting:system
        OptionName: SystemType
        Value: enhanced
      SolutionStackName:
        Ref: SolutionStackName
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
  EBEnvironment:
    Properties:
      ApplicationName:
        Ref: EBApplication
      EnvironmentName:
        Ref: EBApplication
      OptionSettings:
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value:
          Ref: EBInstanceProfile
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value:
          Ref: InstanceType
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: EC2KeyName
        Value:
          Ref: KeyPairName
      - Namespace: aws:ec2:vpc
        OptionName: VPCId
        Value:
          Ref: VpcId
      - Fn::If:
        - UseSubnet
        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          Value:
            Ref: SubnetId
        - Ref: AWS::NoValue
      TemplateName:
        Ref: EBConfigurationTemplate
      VersionLabel:
        Ref: EBApplicationVersion
    Type: AWS::ElasticBeanstalk::Environment
Transform:
- AWS::CodeStar
